# 0911 

In [1]:
#numpy 
#numerical python 
#고성능 수치 계산을 위한 라이브러리 
#벡터나 행렬 연산에 편리한 기능제공 
#모든 원소는 같은 자료형 가능 
#reshape할 때 데이터 갯수를 맞춰야한다 ( 15개면 3,5 o 3,6 x) 
#데이터를 가져오고 데이터의 갯수를 반드시 shape룰 확인해야한다.) 
#(행, 열) 

In [2]:
import numpy as np 
a = np.arange( 15 )
print (a)
a = a.reshape( 3 , 5, order='f' ) # 함수에 옵션을 줄 수 있음  - c- 행부터 할당(기본값) f -열부터 할당 
print( a ) 
print ( type (a) ) 
print ( a. shape) #shape는 함수가 아니라 변수 
print ( a. dtype) #32바이트 정수로 되어있다 데이터 타입 확인 
print ( a. ndim) # 지금 만든 데이터가 몇 차원 데이터인지 확인 
print ( a . size) # 데이터 갯수를 알려줌 
# print (dir (np)) - 넘파이에서 쓸 수 있는 것들을 다 보여주는 것  dir은 함수인데 쓸 수 있는 메서드, 함수, 변수, 클래스 등을 전체적으로 보여줌 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [3]:
#넘파이는 딕셔너리는 안됨 
b = np.array([-1, 2, 5, -3, 0, 7, -9, 7, -4, -7])  #list -데이터 중복 가능 
print(b)

t = (10,20,30,40,50) # tuple 
print (type(t))
t = np.array(t)
print(type(t)) 

s =  {10, 20, 30, 40, 50 } # set - 데이터 중복이 안됨 & 간단한 데이터 
print (type (s))
s = np.array(s)
print( type (s))

[-1  2  5 -3  0  7 -9  7 -4 -7]
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [4]:
print ( b. shape)
print ( b . ndim)
print ( b.dtype) #int 정수 float 실수가 있다. 
print (b)

#print (help ( np.arange ) )


print ( np. abs ( b ) ) # 절대값 
print ( np . sqrt ( np.abs(b) ) ) # sqrt 양의 제곱근 - 루트 / 이중함수 가능 
print ( np.square (b) ) #제곱
print ( np . isnan (b) ) # is함수  nan여부를 물음 nan - true  아니면 false (nan 일때 true, 데이터 값이 있으면 false)
print ( np.sum(b)) #합계 
print ( np. mean (b) ) #평균
print ( np. max(b) ) #최대값 
print ( np. min(b) ) #최소값 
print (np . argmax (b) ) # 최대값의 인덱스 - 제일 큰 값의 위치 
print (np . argmin (b) ) # 최소값의 인덱스 - 제일 작은값의 위치 
print (np. sort (b) ) # 정렬 오름차순 -작은 값부터 
print (np. sort (b) [::-1] ) # 정렬 내림차순 -큰 값부터 [start : end : step ] -를 step으로 주면
print (np. median (b) ) #중간값 

(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
-0.5


In [5]:
np. random.rand (3,3) 

array([[0.8092268 , 0.6642812 , 0.30991038],
       [0.90351855, 0.55418166, 0.25968079],
       [0.88974199, 0.15381642, 0.14280634]])

In [6]:
c = np. zeros (3)
print (c) # 값이 다 0 
d = np. ones ((3,3)) # 값이 다 1 
print (d)
np. random.rand (3,3) 
np.zeros_like(d)
np.ones_like(c)
np.random.randint(1,40,(3,3,3))

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[[ 1,  8, 30],
        [15,  3, 26],
        [ 3, 37, 33]],

       [[ 4, 23, 11],
        [ 4, 36, 10],
        [34, 15, 15]],

       [[25, 39, 18],
        [22, 21, 18],
        [38, 17, 36]]])

In [7]:
np. random.rand (3,3) 

array([[0.35671324, 0.43565978, 0.17533582],
       [0.19834955, 0.33521911, 0.34482813],
       [0.90828974, 0.9781378 , 0.05538126]])

In [8]:
np.zeros_like(d)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones_like(c)

array([1., 1., 1.])

In [10]:
np.random.randint(1,40,(3,3,3))

array([[[20,  8, 39],
        [ 5, 28, 24],
        [39, 31, 10]],

       [[ 8, 16, 16],
        [12, 21, 11],
        [12,  3, 17]],

       [[30, 39,  2],
        [10, 23, 16],
        [39,  6, 27]]])

# 0912

In [20]:
import numpy as np 
c = [[ 1 ,2,3 ] , [4,5,6]]
print(type(c))
c= np.array(c)
print(type(c))

print(np.sum(c) )
print(np.sum(c , axis = 0 ) ) # 0은 행이라는 옵션
print(np.sum(c , axis = 1 ) ) # 1은 열이라는 옵션
print(np.mean(c) ) # 전체평균 
print(np.mean(c , axis = 0 ) )# 0은 행끼리 평균 
print(np.mean(c , axis = 1 ) ) # 1은 열끼리 평균 
print(np.max(c) ) # 전체 최대값
print(np.max(c , axis = 0 ) ) # 0은 행에서 최대값
print(np.max(c , axis = 1 ) ) # 1은 열에서 최대값 




#표준편차 분산 (점과 점사이 거리) 
print (np.std(c)) #표준편차 
print (np. var (c))  #분산 





<class 'list'>
<class 'numpy.ndarray'>
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
6
[4 5 6]
[3 6]
1.707825127659933
2.9166666666666665


In [36]:
#element wise 

d = [10,20,30,40,50]
#print(d+2) #error 
d = np. array(d) 
print (d+2)

e = np.array([1,2,3,4,5])
print (d+e)
print(d**2) 


print (d * np.sin(d))
print(d>35) # 각각의 데이터 크기 비교 
print(np.add (d,e)) # +
print(np.subtract(d,e)) #- 
print(np.multiply(d,e)) # x
print(np.divide(d,e)) # % 

[12 22 32 42 52]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [56]:
f = np. array([ [0,1] , [1,1]]) 
g = np. array([ [2,0] , [3,4] ]) 
print (f*g)
print (f @ g)   #행렬곱 

print( np. dot (f,g)) #행렬곱 - 연산자로도 할 수 있지만 함수도 있다~ 
print ( f. dot(g) )  #또한 행렬곱입니다 


h = np. zeros(10)
print (h) 
i = np. zeros ( (5,5) )  #반드시 튜플로 생성 
print (i) 
j = np . ones (10)
print(j) 


# np. random.random  0~1 사이의 난수 발생 
# np. random . randint 균일분포의 정수 난수 발생 
# np . random . rand 0~1사이의 균일 분포 난수 matrix array 생성 
# np. random . randn 가우시안 표준 정규분포 난수 matrix array 생성 
#np. random.normal 평균, 표준편차, sample 갯수 

k = np.random.random(10) * 100
k = np.array([int(i) for i in k])
print(type (k))
print(k)



print( np.random.randint (10,20))
print ( np. random.rand (5,2) )

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[ 3 62 86 40 41  0 21 16 85 55]
15
[[0.20403744 0.45169914]
 [0.31935469 0.40932408]
 [0.95997962 0.24278963]
 [0.91270237 0.77717625]
 [0.98020789 0.51132903]]


In [62]:
# 슬라이싱 - 리스트 넘파이 판다쓰 다 다르다 
m =  [ i for i in range(10,20)]
print ( m[0:5]) # [ 시작: 끝-1: 간격]

print ( m[0:5:2])
print(m[:])
print(m[5:])
print(m[:-1]) 
print(m[::-1]) #간격이 -1 거꾸로 출력

#ndarray 
w = np. arange (10,20) 
print(w[0:5])
print (w[0:5:2]) 
print(W[:-2]) 




[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]
[10 11 12 13 14]


In [83]:
r = [ [1,2,3,4,5] , [5,6,7,8,9,10] , [11,12,13,14,15]] 
print (r [2][2])
print(r[:][:]) 
print(r[2][:]) 
print(r[1][:2])
print(r[:2][:2])
#print ( r [:,:]) #에러 





s = np.arange (1,16).reshape(3,5)
print ( s ) 
print( s[2][2] ) 
print (s [:][:]) 
print( s[2][:] )
print( s[:2][:1]) #[[12345]]
print( s[:2, :2]) 

print( s[:,:])
print ( s [:-1, :-1])
print ( s [2,2])
print(s [::-1, ::-1]) 

print(s [[0,2]]) 
print (s [:,[1,3,4]])
print(( s[[0,2],[3,4]]) #0행 3열 2행 4열 
      

13
[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[5, 6]
[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[1 2 3 4 5]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3 4]
 [6 7 8 9]]
13
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 2  4  5]
 [ 7  9 10]
 [12 14 15]]


In [84]:
print (s) # 3행 5열 데이터 
print (s. T) #5행 3열 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [91]:
#결합 / 분리 
a = [1,2,3] 
b = [4,5,6] 
for ab in zip (a,b) : 
    print (ab) 
print (list (zip (a,b))) 
print (a + b) 
print ( a* 2) 
#print (a + 2 )



c= np.floor(np. random. rand (2,2) * 100)  
print (c)


d= np.floor(np. random. rand (2,2) * 100)  
print (d)
print( np.hstack( ( c, d ) ) )
print( np.vstack( ( c, d ) ) )
print( c + 2 )






(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]
[[60. 79.]
 [86.  6.]]
[[60. 28.]
 [93. 21.]]
[[60. 79. 60. 28.]
 [86.  6. 93. 21.]]
[[60. 79.]
 [86.  6.]
 [60. 28.]
 [93. 21.]]
[[62. 81.]
 [88.  8.]]


In [92]:
e = np.floor( np.random.rand( 2, 15 ) * 100 )
print( e )
print( np.hsplit( e, 3 ) )               # 3개
for arr in np.hsplit( e, 3 ) :
    print( arr )
for arr in np.hsplit( e, ( 3, 7, 12 ) ) :       # [0:3] [3:7] [7:12] [12:]
    print( arr )

[[44. 59. 33. 89. 55. 48. 49. 43. 68. 98. 10. 41. 37.  3. 54.]
 [12. 19. 35. 91. 66. 12. 50. 69. 22. 91. 21. 62. 47. 59. 48.]]
[array([[44., 59., 33., 89., 55.],
       [12., 19., 35., 91., 66.]]), array([[48., 49., 43., 68., 98.],
       [12., 50., 69., 22., 91.]]), array([[10., 41., 37.,  3., 54.],
       [21., 62., 47., 59., 48.]])]
[[44. 59. 33. 89. 55.]
 [12. 19. 35. 91. 66.]]
[[48. 49. 43. 68. 98.]
 [12. 50. 69. 22. 91.]]
[[10. 41. 37.  3. 54.]
 [21. 62. 47. 59. 48.]]
[[44. 59. 33.]
 [12. 19. 35.]]
[[89. 55. 48. 49.]
 [91. 66. 12. 50.]]
[[43. 68. 98. 10. 41.]
 [69. 22. 91. 21. 62.]]
[[37.  3. 54.]
 [47. 59. 48.]]


In [93]:
f = np.array( [ 1, 2, 3, 4, 5 ] )
g = np.array( [ 'A', 'B', 'C', 'D', 'E' ] )
h = np.array( [ True, True, False, False, True ] )
# 삼항연산              조건 ? 참 : 거짓 
#                       참 if 조건 else 거짓
print( [ x if z else y for x, y, z in zip( f, g, h ) ] )

print( np.where( h, f, g ) )
print( np.where( f < 3, '작다', '크다' ) )
print( np.where( h, '참', '거짓' ) )

[1, 2, 'C', 'D', 5]
['1' '2' 'C' 'D' '5']
['작다' '작다' '크다' '크다' '크다']
['참' '참' '거짓' '거짓' '참']


In [94]:
i = np.arange( 10 )
np.save( 'i.npy', i )
ii = np.load( 'i.npy' )
print( type( ii ) )             

j = np.arange( 10 )
k = np.arange( 20 )
np.savez( 'jk.npz', x=j, y=k )
jk = np.load( 'jk.npz' )
print( type( jk ) )
print( jk['x'] )
print( jk['y'] )

<class 'numpy.ndarray'>
<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
